addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: fbae8224-412b-495b-bfb6-3523be292595
after_success:
- ./df-build.sh
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
branches:
  only:
  - develop
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: JwCmjYm7szOBRLEL24GvPumwQNokA6bcdpP1X5Zmj2QhGIFKlYeOHkgkiRQt+SSWH6ClcBSHWtCi9+OlvC4O1vOXoH4nuq2a3xeIP7t+oJDWqTM8J34zEzUX9lG1rHI87YbuTWWN8+6HsbUTbfHMLWxX+UgyYgaloqt5JiTyB7A=
  - secure: sLJrG63Qgs9kXxGrVoLYuO5hV79t2RoEKoAFzMSTeCjG1JOxWWnuvlIzTnMQD3NU0IJy1YQrkuU8wWvjpk5+3Ue0/TZDDR2psqEomYyphnfRVUH/U593dbXxK6XREE7n/X/dvlaTXq2YLcKrO09SJUSwwlDt0LjkGLzYfHziN5s=
jdk:
- oraclejdk8
language: java
matrix:
- LC_ALL=C
- LC_ALL=pl_PL
- LC_ALL_zh_CN
notifications: {}
script: ' if [ ${TRAVIS_PULL_REQUEST} = ''false'' ]; then mvn clean deploy --settings
  target/travis/settings.xml; else mvn clean verify --settings target/travis/settings.xml;
  fi'
sudo: false
# Modified by Insights Service at 2016-05-27 11:49:57.467049
